Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"

  vms = [
    { name: "vm.manager", hostname: "vm.manager", ip: "192.168.56.10" },
    { name: "vm.worker1", hostname: "vm.worker1", ip: "192.168.56.11" },
    { name: "vm.worker2", hostname: "vm.worker2", ip: "192.168.56.12" },
    { name: "vm.worker3", hostname: "vm.worker3", ip: "192.168.56.13" },
    { name: "vm.worker4", hostname: "vm.worker4", ip: "192.168.56.14" }
  ]

  vms.each do |vm|
    config.vm.define vm[:name] do |node|
      node.vm.hostname = vm[:hostname]
      node.vm.network "private_network", ip: vm[:ip]

      # Common Docker installation
      node.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
        apt-get update -y
        apt-get install -y docker-ce docker-ce-cli containerd.io
        systemctl enable docker
        systemctl start docker
      SHELL

      # if vm[:name] == "vm.manager"
      #   # Manager-specific provisioning
      #   node.vm.provision "file", source: "../docker", destination: "/home/vagrant/docker"
      #   node.vm.provision "shell", inline: <<-SHELL
      #     docker swarm init --advertise-addr #{vm[:ip]}
      #     docker swarm join-token worker -q > /vagrant/worker_token
      #   SHELL
      # else
      #   # Worker-specific provisioning
      #   node.vm.provision "shell", inline: <<-SHELL
      #     MANAGER_IP="192.168.56.10"
      #     TOKEN=$(cat /vagrant/worker_token)
      #     docker swarm join --token $TOKEN $MANAGER_IP:2377
      #   SHELL
      # end
    end
  end
end
